name: steganosaurus
description: A steganography flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  easy_localization: ^3.0.1
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.18


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
      - assets/translations/
      
  uses-material-design: true
